name: CI/CD Diet Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib seaborn python-dotenv azure-storage-blob

    - name: Run Data Analysis Script
      run: |
        python3 data_analysis.py

    - name: Upload CSVs and Images as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: diet-analysis-results
        path: |
          All_Diets_cleaned.csv
          All_Diets_NP_Results.csv
          avg_protein_bar_chart.png
          protein_scatter_plot.png
          total_macros_histogram.png
